### ISSUE TITLE
Menu: Brands and Clearance not found

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Mechtric#18]
![image](https://cloud.githubusercontent.com/assets/18568310/15314846/da788ef6-1c46-11e6-81fb-f728c4bc5162.png)

**Comment by ravititan** [comment]
The implementation is done as per the Design & Scope provided, post release the PM (Hanrie) might have removed those categories/pages while updating the content. 
It would be better if you can please get clarify from Hanrie on this. Thanks

**Comment by ricatitan** [comment]
QA Lead: 
Hi Ravi, I don't think that the PM has already uploaded content since only the header menu is changed while the rest remained as is. I can't get confirmation from Hanrie as well.  Better follow the design for now and let them change later when they need to add final content.

Thanks
