### ISSUE TITLE
About Us - Tools : Image can't be seen in I.E browser

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Mechtric#22]
![image](https://cloud.githubusercontent.com/assets/18568310/15314995/a24056c6-1c47-11e6-970b-f8e69d91f477.png)

**Comment by ravititan** [comment]
The images are showing in IE browser.
![mechtric_qa-issue-22](https://cloud.githubusercontent.com/assets/13450891/15417849/ab7e81ae-1e77-11e6-90d9-4eedf495f72b.jpg)

**Comment by ricatitan** [comment]
Image is still broken and image should not be clickable.
![image](https://cloud.githubusercontent.com/assets/18568310/15458443/abf0d46e-20cc-11e6-919a-1a3ceb3c753b.png)

**Comment by ricatitan** [comment]
Remove the broken image below
![image](https://cloud.githubusercontent.com/assets/18568310/15488843/192ac2c2-218d-11e6-9c83-319546ae7015.png)
