### ISSUE TITLE
Contact Us: Contact numbers cant be click to call

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Mechtric#30]
![image](https://cloud.githubusercontent.com/assets/18568310/15316984/177c5e76-1c52-11e6-82ff-ddfb397ecd53.png)

**Comment by ravititan** [comment]
It is as per the Standards & Guidlines.Please check the guidelines under section G-8.
![mechtric_qa-issue-30](https://cloud.githubusercontent.com/assets/13450891/15419166/e7345aac-1e81-11e6-8ebe-da5990389787.jpg)

**Comment by ricatitan** [comment]
What I mean is contact numbers  should be click to call. Error: Mobile can't be click to call. 
![image](https://cloud.githubusercontent.com/assets/18568310/15458127/c19c428e-20c8-11e6-9f44-5b4cbd3378c5.png)
