### ISSUE TITLE
Leadins: Post title has incorrect font style and font size

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Mechtric#5]
![image](https://cloud.githubusercontent.com/assets/18568310/15310782/057d6d68-1c26-11e6-98bb-b9695ef83ea6.png)

**Comment by ravititan** [comment]
![mechtric_qa-issue-5](https://cloud.githubusercontent.com/assets/13450891/15393629/02814ebe-1dec-11e6-997f-a7f137cfb920.jpg)
