### ISSUE TITLE
News Single: Incorrect font style

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Mechtric#9]
![image](https://cloud.githubusercontent.com/assets/18568310/15312404/51dc91f6-1c36-11e6-8c51-1431f76293a5.png)

**Comment by ravititan** [comment]
![mechtric_qa-issue-9](https://cloud.githubusercontent.com/assets/13450891/15393364/80ba087c-1dea-11e6-9122-abdb4680335b.jpg)
